# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-28 13:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_b', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='email',
            field=models.CharField(default='', max_length=64),
            preserve_default=False,
        ),
    ]
