# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-08-17 17:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_b', '0002_email_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='email',
            name='type',
        ),
        migrations.RemoveField(
            model_name='phone',
            name='phone_number',
        ),
        migrations.AlterField(
            model_name='address',
            name='flat_number',
            field=models.CharField(max_length=16),
        ),
        migrations.AlterField(
            model_name='phone',
            name='type',
            field=models.CharField(choices=[(0, 'Private'), (1, 'Business')], max_length=32),
        ),
    ]
