# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-08-18 19:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_b', '0009_remove_phone_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='phone',
            name='phone_number',
            field=models.CharField(default=0, max_length=32),
            preserve_default=False,
        ),
    ]
